In [51]:
#Mounting Google Drive to Colab
from google.colab import drive
drive.mount('/content/drive')
print("Drive Mounted")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Drive Mounted

In [52]:
import sys
print(f"Python version: {sys.version}")

Python version: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]

In [53]:
# Adding Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("All libraries imported successfully")

All libraries imported successfully

In [54]:
FILE_PATH ='/content/drive/MyDrive/CARISURG/WEEK_0/EmergencyTriageDataset_Reduced_Dirty.csv'

df_raw = pd.read_csv(FILE_PATH)
print(f"Dataset successfully loaded: {df_raw.shape[0]} rows x {df_raw.shape[1]} columns")
print(f"Columns Headings: {list(df_raw.columns)}")

Dataset successfully loaded: 2205 rows x 11 columns
Columns Headings: ['ID', 'Age', 'Gender', 'GCS', 'SBP', 'DBP', 'MAP', 'pulse', 'Temp', 'RR', 'Fio2']

In [55]:
# Checking the first few columns
df_raw.head(15)

    ID  Age  Gender   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2
0    1   34       0  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0
1    2   20    Male  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0
2    3   77  Female  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0
3    4   23       0   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0
4    5   86  FEMALE  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0
5    6   42    Male  15.0  100   60.0   73.33   99.0  37.0  20.0   21.0
6    7   75  Female  15.0  120   80.0   93.33   99.0  37.0  25.0   21.0
7    8   25    Male  15.0  100   50.0   66.67   85.0  37.0  25.0   21.0
8    9   67       0  15.0  110   70.0   83.33   78.0  37.0  16.0   21.0
9   11   82  Female  15.0  153   82.0  105.67  130.0  37.0  19.0   21.0
10  12   78       0  15.0  150   90.0  110.00   85.0  37.0  16.0   21.0
11  13   80       1  13.0  110   90.0   96.67   85.0  37.0  19.0   40.0
12  14   81       0  13.0  120   80.0   93.33  100.0  37.0  15.0   21.0
13  15   53  Female  13.0  152   89.0  110.00   63.0  37.0  24.0   21.0
14  16   47       0  13.0  130   70.0   90.00   98.0  36.5  16.0    NaN

In [56]:
print(df_raw.dtypes)

ID          int64
Age         int64
Gender     object
GCS        object
SBP        object
DBP       float64
MAP       float64
pulse      object
Temp       object
RR        float64
Fio2      float64
dtype: object

In [57]:
# Cleaning the Gender Column
print("Unique Values in Gender:")
print(df_raw['Gender'].unique())
print(f"\nTotal number of different values: {df_raw['Gender'].nunique()}")

Unique Values in Gender:
['0' 'Male' 'Female' 'FEMALE' '1' 'MALE']

Total number of different values: 6

In [58]:
# Counting the total gender value
print("Gender Value total:")
print(df_raw['Gender'].value_counts())

Gender Value total:
Gender
1         422
MALE      379
Male      375
FEMALE    366
Female    340
0         323
Name: count, dtype: int64

In [59]:
# Cleaning Gender

gender_map = {
    'Female': 'F',
    'FEMALE': 'F',
    '0':      'F',
    'Male':   'M',
    'MALE':   'M',
    '1':      'M'
}
df_raw['Gender_Clean'] = df_raw['Gender'].astype(str).map(gender_map)

In [60]:
#Verifying
print("After cleaning:")
print(df_raw['Gender_Clean'].value_counts(dropna=False))
print(f"\nAny NaN values? {df_raw['Gender_Clean'].isnull().sum()}")

After cleaning:
Gender_Clean
M    1176
F    1029
Name: count, dtype: int64

Any NaN values? 0

In [61]:
#Replacing Original Column

df_raw = df_raw.drop(columns=['Gender'])
df_raw = df_raw.rename(columns={'Gender_Clean': 'Gender'})

print("'Gender' Column after cleaning:")
print(df_raw['Gender'].value_counts())
print(f"Data type: {df_raw['Gender'].dtype}")

df_raw.head()

'Gender' Column after cleaning:
Gender
M    1176
F    1029
Name: count, dtype: int64
Data type: object

   ID  Age   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2 Gender
0   1   34  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0      F
1   2   20  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0      M
2   3   77  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0      F
3   4   23   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0      F
4   5   86  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0      F